### PR TITLE
feat(themes): new themes and automatic theme switcher!

### PR DESCRIPTION
**Pull request by catdadcode**
# New Default Themes!

1. **april_fools** - 🤡, 🎭, 🃏, 🎉, 😂, 🙃, 🎈, 🎁, 🤣, 😜
2. **arcade** - 🎮 🕹️ 👾 💾 ⚔️ 🛡️ 🏰
3. **art** - 🎨 🖼️ 🖌️ 🎭 🎶 📚 🖋️
4. **bakery** - 🍞 🥖 🥐 🍩 🍰 🧁 🍪
5. **beach** - 🌴 🏖️ 🍹 🌅 🏄 🐚 🌞
6. **binary** - 0, 1
7. **bugs** - 🐞, 🐜, 🪲, 🦗, 🕷️, 🕸️, 🐛
8. **business** - 💼, 🖊️, 📈, 📉, 💹, 💲, 🏢
9. **candy** - 🍬 🍭 🍫 🍩 🍰 🧁 🍪
10. **cards** - ♠️, ♥️, ♦️, ♣️, 🃏
11. **carnival** - 🎪 🎭 🍿 🎠 🎡 🎈 🤹
12. **casino** - 🎰 ♠️ ♦️ ♣️ ♥️ 🎲 🃏
13. **cats** - 🐱, 🦁, 🐯, 🐈, 🐅, 🐆
14. **coffee** - ☕ 🥐 🍰 🍪 🍩 🥛 🍫
15. **cyberpunk** - 🌃 💿 🕶️ ⚙️ 🖥️ 🎮 🔌
16. **deepsea** - 🐠 🐙 🦈 🌊 🦑 🐡 🐟
17. **desert** - 🌵 🐪 🏜️ 🌞 🦂 🪨 💧
18. **dice** - ⚀, ⚁, ⚂, ⚃, ⚄, ⚅
19. **diner** - 🍔 🍟 🥤 🍳 🥞 🥓 🍦
20. **easter** - 🐣 🐥 🐤 🥚 🌸 🍫 🐇 🌷 🌼 🍃 🦋 🍬 🌈 🎀 💒
21. **emotional** - 😀, 😃, 😄, 😁, 😆, 😅, 😂, 🤣, 😊, 😇, 🙂, 🙃, 😉, 😌, 😍, 😘, 😗, 😙, 😚, 😋, 😛, 😝, 😜, 🤪, 🤨, 🧐, 🤓, 😎, 🤩, 😏, 😒, 😞, 😔, 😟, 😕, 🙁, ☹️, 😣, 😖, 😫, 😩, 🥺, 😢, 😭, 😤, 😠, 😡, 🤬, 🤯, 😳, 🥵, 🥶, 😱, 😨, 😰, 😥, 😓, 😶, 😐, 😑, 😬, 😯, 😦, 😧, 😮, 😲, 🥱, 😴, 🤤, 😪, 😵, 🤐, 🥴, 🤢, 🤮, 🤕, 🤒, 😷, 🥰, 😸, 😺, 😻, 😼, 😽, 🙀, 😿, 😹
22. **explorer** - 🌍 🌐 🗺️ 🔍 ⛺ 🌄 🧭
23. **fantasy** - 🐉 🏰 🪄 🧙 🛡️ 🗡️ 🌌 👑
24. **farm** - 🐄 🐖 🐓 🌾 🍎 🍏 🚜
25. **garden** - 🌱, 🌸, 🌻, 🌿, 🍂, 🍃, 🌾
26. **halloween** - 🎃, 👻, 🦇, 🕷️, 🕸️, 🦉, 🔮, 💀, 👽, 🌙, 🍬, 🍭, 🖤, 🔪, 🧛, 🪦, 😱, 🙀, 🌕, ⚰️
27. **jungle** - 🦜 🦍 🌴 🐅 🐍 🌺 🦎
28. **leaves** - 🍂 🍁 🍀 🌿      
29. **lunar** - 🌑, 🌒, 🌓, 🌔, 🌕, 🌖, 🌗, 🌘
30. **magical** - 🔮 🌟 🧹 🎩 🐇 🪄 💫
31. **mathematical** - ➕, ➖, ✖️, ➗, ≠, ≈, ∞
32. **matrix** - 0 1 ⌘ ∑ ∆ Λ ψ ⊕ ⊖ ∴ ≡ Ω µ ∂ Φ ν
33. **medieval** - 🏰 🛡️ ⚔️ 🎠 👑 🏹 🍺
34. **musical** - 🎵 🎶 🎤 🎷 🎸 🎺 🎻
35. **mystery** - 🕵️, 🔎, 🔒, 🔑, 📜, 🖋️, 🗝️
36. **mystical** - 🔮 🌕 🌟 📜 ✨ 🔥 💫
37. **new_year** - 🎆 🎉 🍾 🥂 ⏰ 🕛 🎈 🌟 ✨ 🎊 🥳 💫 📅 2️⃣ 0️⃣ 2️⃣ 4️⃣
38. **nocturnal** - 🦉 🌙 🦇 🌌 🌠 🔭 🌚
39. **ocean** - 🌊 🐠 🐟 🐡 🐬 🐳 🦈 🐚 ⛵
40. **pirate** - ☠️ ⚓ 🏴‍☠️ 🗺️ 🦜 ⚔️ 💰
41. **retro** - 📻 📺 🎞️ 📼 🎙️ 🕰️ ☎️
42. **snow** - ❄️    ❅ ❇ * .
43. **spa** - 🕯️ 🛁 🌸 💆 🍵 🧘 💅
44. **space** - 🪐 🌌 ⭐ 🌙 🚀 🛰️ ☄️ 🌠 👩‍🚀
45. **sports** - ⚽ 🏀 🏈 ⚾ 🎾 🏓 🏒
46. **spring** - 🐑 🐇 🦔 🐣 🦢 🐝 🌻 🌼 🌷 🌱 🌳 🌾 🍀 🍃 🌈
47. **stars** - ★ ⭐ ✮ ✦ ✬ ✯ 🌟
48. **steampunk** - ⚙️ 🕰️ 🎩 🚂 🧭 🔭 🗝️
49. **st_patricks_day** - 🍀 🌈 💚 🇮🇪 🎩 🥔 🍺 🍻 🥃 🍖 💰 🌟 🍵 🐍 🪄
50. **summer** - 😎 🏄 🏊 🌻 🌴 🍹 🏝️ ☀️  🌞 🕶️ 👕 ⛵ 🥥 🌊
51. **temporal** - 🕐, 🕑, 🕒, 🕓, 🕔, 🕕, 🕖, 🕗, 🕘, 🕙, 🕚, 🕛
52. **thanksgiving** - 🦃 🍂 🍁 🌽 🥧 🍠 🍎 🍖 🍗 🥖 🥔 🍇 🍷 🌰 🥕
53. **travel** - ✈️, 🌍, 🗺️, 🏨, 🧳, 🗽, 🚂
54. **tropical** - 🌴 🍍 🍉 🥥 🌺 🐢 🌊
55. **urban** - 🏢 🚕 🚇 🍕 🚦 🛴 🎧
56. **us_independence_day** - 🇺🇸 🎆 🗽 🦅 🌭 🍔 ⭐ 🎉 🥳 🍻 🥁 🎵 🎶 🚀 💥v
57. **valentines_day** - ❤️ 💖 💘 💝 💕 💓 💞 💟 💌 🌹 🍫 💐 💍 🍷 🕯️
58. **wilderness** - 🌲 🐺 🦌 🏞️ 🔥 ⛺ 🌌
59. **wildwest** - 🤠 🐎 🌵 🔫 ⛏️ 🌄 🚂
60. **winter_wonderland** - ❄️ ⛄ 🌨️ 🎿 🛷 🏔️ 🧣
61. **xmas** - 🎄 🎁 🤶 🎅 🛷 ❄ ⛄ 🌟 🦌 🎶 ❄️    ❅ ❇ *
62. **zodiac** - ♈, ♉, ♊, ♋, ♌, ♍, ♎, ♏, ♐, ♑, ♒, ♓
63. **zoo** - 🦁 🐘 🦓 🦒 🦅 🦉 🐆

# Automatic Holiday Themes!

```lua
  holidays = { -- can be nil or {} to disable automatic holidays.
    new_year = { month = 1, day = 1 },
    valentines_day = { month = 2, day = 14 },
    st_patricks_day = { month = 3, day = 17 },
    easter = M.calculate_easter(year), -- holiday date helper functions
    april_fools = { month = 4, day = 1 },
    us_independence_day = nil, -- can be nil to disable default holiday
    halloween = { month = 10, day = 31 },
    us_thanksgiving = M.calculate_us_thanksgiving(year),
    xmas = { start_date = { month = 12, day = 24 }, end_date = { month = 12, day = 25 } },
  }
```

### CODE REVIEW

**Comment by Dronakurl** [comment]
Argl! I am so stupid. I should have checked the PRs first. This is so much better than the PR, I submitted today!

**Comment by catdadcode** [comment]
> Argl! I am so stupid. I should have checked the PRs first. This is so much better than the PR, I submitted today!

Oh no! I'm sorry lol. You can use my version already by just changing `"folke/drop.nvim"` to `"catdadcode/drop.nvim"`. Let me know if you encounter any issues. It's been stable for my needs for the last couple months or so.

Hopefully it gets merged but I imagine this plugin is not a high priority lol.

**Comment by catdadcode** [comment]
Oh and also here's my personal config for it which expands the date ranges for Halloween, Thanksgiving, and Christmas since I like them active fore more of their respective months 😄

There's also some custom logic in there for swapping my theme based on my current project path. So when I'm in a work project it actually uses a custom solar power theme (I work for a solar power company) instead of my usual default theme. And the default themes get overridden by the holiday scheduler 🙂 

https://github.com/catdadcode/.dotfiles/blob/main/nvim/lua/plugins/drop.lua

**Comment by catdadcode** [comment]
😢

**Comment by NeckBeardPrince** [comment]
@folke can we merge this?

**Comment by folke** [comment]
I've refactored the code and also added default themes based on the seasons.

**Comment by folke** [comment]
ty!

**Comment by catdadcode** [comment]
Yay! Thank you 🙏. I know this plugin is probably like the lowest priority. Love your work!

**Pull request merged**
